### ISSUE TITLE
Substitution inside css files

### ISSUE THREAD

**Issue by MaikMichel** [OraOpenSource/apex-nitro#284]
### Issue Description
Hi,

I'm referencing a background-image inside my css files
```css
  .login-logo{
    ...
    background-image: url("#APP_IMAGES#img/logo.png");
    ...
  }
```

Is there any chance to replace that too?

**Comment by vincentmorneau** [comment]
you would be better off with relative paths there:

```css
  .login-logo{
    ...
    background-image: url("../img/logo.png");
    ...
  }
```
